apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: return
  namespace: default
spec:
  action: return
  class: Main
  method: getnum
  value: '9999' 
  returnValue: '9999' 
  mode: all  
  selector:
    namespaces:
      - default  
    labelSelectors:
      app: helloworld 
  duration: "30s"  
